# Generated by Django 5.0.2 on 2024-05-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('legs', 'Legs'), ('arms', 'Arms'), ('abs', 'Abs'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('equipment', 'Equipment'), ('no_equipment', 'No_equipment')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('icon', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
