# Generated by Django 5.0.2 on 2024-05-06 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='icon',
        ),
    ]
