# Generated by Django 5.0.2 on 2024-05-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_exercise_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='type2',
            field=models.CharField(choices=[('equipment', 'Equipment'), ('no_equipment', 'No_equipment')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('legs', 'Legs'), ('arms', 'Arms'), ('abs', 'Abs'), ('back', 'Back'), ('chest', 'Chest'), ('shoulders', 'Shoulders')], max_length=20),
        ),
    ]
