# Generated by Django 5.0.2 on 2024-05-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userexerciseplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexerciseplan',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
