# Generated by Django 5.0.2 on 2024-05-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userexerciseplan_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexerciseplan',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
