# Generated by Django 5.0.2 on 2024-05-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userexerciseplan_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexerciseplan',
            name='plan_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
