# Generated by Django 5.0.2 on 2024-05-10 15:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_userexerciseplan_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexerciseplan',
            name='plan_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
