# Generated by Django 5.0.2 on 2024-03-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymsite', '0002_articles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='text',
            field=models.CharField(default='Default', max_length=2000),
        ),
    ]
