# Generated by Django 5.0.2 on 2024-03-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymsite', '0003_articles_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='text',
            field=models.TextField(default='Default', max_length=2000),
        ),
    ]
