# Generated by Django 5.0.2 on 2024-03-25 19:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymsite', '0005_alter_articles_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='text',
            field=ckeditor.fields.RichTextField(default='Default', max_length=10000),
        ),
    ]
