# Generated by Django 5.0.2 on 2024-03-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymsite', '0008_abonement_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonement',
            name='type',
            field=models.CharField(default='Default', max_length=100),
        ),
    ]
