# Generated by Django 5.0.2 on 2024-03-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymsite', '0009_abonement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonement',
            name='type',
            field=models.CharField(choices=[('заняття', 'Заняття'), ('місяці', 'Місяці')], max_length=20),
        ),
    ]
