# Generated by Django 5.0.2 on 2024-03-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymsite', '0011_alter_abonement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonement',
            name='description',
            field=models.TextField(default='Default', max_length=500),
        ),
    ]
