# Generated by Django 5.0.2 on 2024-03-29 18:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymsite', '0012_alter_abonement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonement',
            name='description',
            field=ckeditor.fields.RichTextField(default='Default', max_length=500),
        ),
    ]
